// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-z2D4PbJngODz6KnE0WASTuk9CR9Z4M',
    appId: '1:1060359976472:android:f2170f02d32b98aecdb56d',
    messagingSenderId: '1060359976472',
    projectId: 'territory-capture-43e44',
    databaseURL: 'https://territory-capture-43e44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'territory-capture-43e44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2FLp-YKtiN9qYAXFrheGSmttYkXZMa5U',
    appId: '1:1060359976472:ios:dfcf2dee6c7ec83ccdb56d',
    messagingSenderId: '1060359976472',
    projectId: 'territory-capture-43e44',
    databaseURL: 'https://territory-capture-43e44-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'territory-capture-43e44.firebasestorage.app',
    iosBundleId: 'me.territorycapture.territoryCapture',
  );
}
